language: rust
cache: cargo

before_deploy:
  - mkdir cfn-guard-$TRAVIS_OS_NAME
  - |
    if [[ "$TRAVIS_OS_NAME" == "windows" ]]
    then
      cp -f target/release/cfn-guard.exe ./cfn-guard-$TRAVIS_OS_NAME/
    else
      cp ./target/release/cfn-guard ./cfn-guard-$TRAVIS_OS_NAME/
    fi
  - cp LICENSE ./cfn-guard-$TRAVIS_OS_NAME/
  - cp NOTICE ./cfn-guard-$TRAVIS_OS_NAME/
  - cp README.md ./cfn-guard-$TRAVIS_OS_NAME/
  - tar czvf ./cfn-guard-$TRAVIS_OS_NAME.tar.gz ./cfn-guard-$TRAVIS_OS_NAME

deploy:
  provider: releases
  file_glob: true
  api_key:
    secure: rHRd6poek+A69E8tpW+HZrZHj5y0Q7Wg2CHR5dMOtg9sMMhojXtIOyNPvIDsCMJmfxAILfIrOm6ka/XISqDLHh1hlnMBfmMnC2vfT8tEGSeBww3XKWqWpSG3wyRozK66fLPA1EcSV7e6/hEIlEGYv26040QMqnyRsSxfiXQrt2IpJbi8V6RSQKRVD/bhWrZXpUzGElzj1CWtPT8MMQsCZFFw8v1Rnbq2pKzz7UC+09YqucS9uxkqVrJlaF16bcN/iAbT7dIU5xGpSoJkY55lDfJMowcs09qX1IO51gG6W3xFK106+W7XOK/9sTdk80tEBD+QBZdC8jtJhu0h4Z30xitsRc6yZuWINodbaYkksGxiqLpyf4wClCdKpIf4AzlmkNjXf9QPH0/rcEaCnD1I8Ojxfm52q9zsIw+L4aZX0rA/hfDM/ungTSd+hMN3mAHAEFdOLYamJzQQs0MdyOGPNpS5GSmlf8PFqSCcCh+3qjnbjfTr97e/8gWJw3pjRx/W0jYs3CLnaTnmw78Bo81y5EnY/0yujefBNPlXYUZ7ghvRZaQ97WjjTFyl/x5uLRYFVgAWppg78wJn671oq0gp9dtxLwHUf2q3g0sK38C/O3SXMSaa+J2Kvf6oc7XB0U9GO0H89gv+8rmMpvAJrVko47Ud4yEcI2X21oNxywQiYV4=
  file: cfn-guard-$TRAVIS_OS_NAME.tar.gz
  on:
    repo: jotompki/cloudformation-guard
    all_branches: true
  skip_cleanup: 'true'

matrix:
  include:
  - name: Linux Binary
    env: TARGET=x86_64-unknown-linux-musl
    rust: nightly
    script: cargo build --verbose --release
    addons:
      apt:
        packages:
          - musl-tools
  - name: macOS Binary
    env: MACOSX_DEPLOYMENT_TARGET=10.7 TARGET=x86_64-apple-darwin
    os: osx
    rust: nightly
    script: cargo build --verbose --release
  - name: Windows Binary
    os: windows
    rust: nightly
    script: cargo build --verbose --release
